#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: "{build}"

# branches to build 
branches:
  # whitelist
  only:
    - patch-1
  # blacklisted
  except:
    - /.*/    # exclude all branches but whitelisted
    
#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
  - Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  # if 0 then restore cache (default); cache updates in the end of the successful build
  - ps: IF (0) {$env:APPVEYOR_CACHE_SKIP_RESTORE = "true"}

# environment variables
environment:
  # there common variables for all groups. I have any
  # first group, maybe not needed at all
  matrix:
    - platform: x64
      configuration: Release
      # OpenShot x64 dependencies folder
      OPENSHOT_DEPS_DIR: 'C:\OPSH\Deps'
      # OpenShot x64 installation folder
      OPENSHOT_INST_DIR: 'C:\OPSH\OpenShotVideoEditor'
      # Python folder
      PYTHONHOME: 'C:\Python37-x64'
      # Specifies where the source of Qt libs lies
      #   IN_MSYS2     if MSYS2 package is used or PyQt should be recompiled (3 parts), slow
      #   DEPS_FOLDER  if custom Qt package is used (no debug dlls), fast
      OPENSHOT_QT_SOURCE: 'DEPS_FOLDER'
      # Specifies is the PyQt5 module already installed in Python
      OPENSHOT_PYQT5: 'Not_installed_yet'

# build cache to preserve files/folders between builds
cache:
  # ffmpeg
  - '%APPVEYOR_BUILD_FOLDER%\downloads\ffmpeg-4.2-win64-dev.zip'
  - '%APPVEYOR_BUILD_FOLDER%\downloads\ffmpeg-4.2-win64-shared.zip'
  - '%OPENSHOT_DEPS_DIR%'
  - '%APPVEYOR_BUILD_FOLDER%\downloads\last-libopenshot.txt'
  - '%APPVEYOR_BUILD_FOLDER%\downloads\last-libopenshot-audio.txt'
  - '%APPVEYOR_BUILD_FOLDER%\downloads\cxFrsrc.zip'
  - '%APPVEYOR_BUILD_FOLDER%\downloads\PyQt5sipsrc.zip'
  - '%APPVEYOR_BUILD_FOLDER%\downloads\PyQt5src.zip'
  - '%APPVEYOR_BUILD_FOLDER%\downloads\OpenShot-Ext-Deps-win-x64-N491m01.7z'
  - '%OPENSHOT_INST_DIR%\python-%PLATFORM%.7z'

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
#platform:
#  - x64

# build Configuration, i.e. Debug, Release, etc.
#configuration:
#  - Release

# scripts that run after cloning repository
install:
  - cmd: 'echo Start install at: & time /t'
  - cmd: '%APPVEYOR_BUILD_FOLDER%\CI\install-win-av.cmd'
  - cmd: 'echo End install at: & time /t'

# Build settings
build: off # disable MSBuild

# to run custom scripts instead of automatic MSBuild
build_script:
  - cmd: 'echo Start building at: & time /t'
  - cmd: '%APPVEYOR_BUILD_FOLDER%\CI\build-win-av.cmd'
  - cmd: 'echo End building at: & time /t'

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\CI\pack-win-av.cmd'
  - ps: Push-AppveyorArtifact "$Env:OPENSHOT_INST_DIR\openshot-win-$Env:PLATFORM.7z" -FileName "OpenShot-$(git --git-dir=$Env:APPVEYOR_BUILD_FOLDER\.git describe --always --abbrev=8)-win-$Env:PLATFORM-N$Env:APPVEYOR_BUILD_NUMBER.7z"
  - ps: Push-AppveyorArtifact "$Env:OPENSHOT_INST_DIR\openshot-deps-win-$Env:PLATFORM.7z" -FileName "OpenShot-Deps-$(git --git-dir=$Env:APPVEYOR_BUILD_FOLDER\.git describe --always --abbrev=8)-win-$Env:PLATFORM-N$Env:APPVEYOR_BUILD_NUMBER.7z"
  - ps: IF ( -not (Test-Path -Path "$Env:APPVEYOR_BUILD_FOLDER\downloads\openshot_pyqt5.txt")) {Push-AppveyorArtifact "$Env:OPENSHOT_INST_DIR\python-$Env:PLATFORM.7z" -FileName "Python3-$Env:PLATFORM-withPyQt5-5122-win-N$Env:APPVEYOR_BUILD_NUMBER.7z"}

test: off
